import type { ContainerRecipe, Directive } from "@/components/common";

const WINDOWS_ABSOLUTE_PATH = /^[A-Za-z]:[\\/]/;
const TEMPLATE_PATTERN = /\{\{|\{%|\}\}|\%\}/;

function normalizeRecipePath(input: string): string | null {
    if (!input || WINDOWS_ABSOLUTE_PATH.test(input) || input.startsWith("/")) {
        return null;
    }

    const parts = input
        .split(/[\\/]/)
        .map((part) => part.trim())
        .filter((part) => part.length > 0);

    if (parts.length === 0 || parts.includes("..")) {
        return null;
    }

    return parts.join("/");
}

function splitCopyArgs(copy: string[] | string): string[] {
    if (Array.isArray(copy)) {
        return copy.filter((entry): entry is string => typeof entry === "string");
    }

    return copy
        .split(/\s+/)
        .map((entry) => entry.trim())
        .filter((entry) => entry.length > 0);
}

function collectDeclaredFileNames(
    directives: Directive[],
    names: Set<string>,
): void {
    for (const directive of directives) {
        if ("file" in directive && directive.file.name.trim()) {
            names.add(directive.file.name.trim());
        }

        if ("group" in directive) {
            collectDeclaredFileNames(directive.group, names);
        }
    }
}

function collectSupportFilesFromDirectives(
    directives: Directive[],
    declaredNames: Set<string>,
    files: Set<string>,
): void {
    for (const directive of directives) {
        if ("file" in directive) {
            const filename = directive.file.filename?.trim();
            if (filename && !TEMPLATE_PATTERN.test(filename)) {
                const normalized = normalizeRecipePath(filename);
                if (normalized) {
                    files.add(normalized);
                }
            }
        }

        if ("copy" in directive) {
            const args = splitCopyArgs(directive.copy);
            if (args.length >= 2) {
                for (const source of args.slice(0, -1)) {
                    if (TEMPLATE_PATTERN.test(source) || declaredNames.has(source)) {
                        continue;
                    }

                    const normalized = normalizeRecipePath(source);
                    if (normalized) {
                        files.add(normalized);
                    }
                }
            }
        }

        if ("group" in directive) {
            collectSupportFilesFromDirectives(directive.group, declaredNames, files);
        }
    }
}

export function collectRecipeSupportFiles(recipe: ContainerRecipe): string[] {
    const declaredNames = new Set<string>();

    for (const file of recipe.files ?? []) {
        if (file.name.trim()) {
            declaredNames.add(file.name.trim());
        }
    }

    collectDeclaredFileNames(recipe.build.directives, declaredNames);

    const files = new Set<string>();
    collectSupportFilesFromDirectives(recipe.build.directives, declaredNames, files);
    return Array.from(files).sort();
}

export function buildValidationSupportFiles(recipe: ContainerRecipe): {
    files: Record<string, string>;
    warnings: string[];
} {
    const requiredFiles = collectRecipeSupportFiles(recipe);

    if (requiredFiles.length === 0) {
        return { files: {}, warnings: [] };
    }

    const files = Object.fromEntries(
        requiredFiles.map((path) => [
            path,
            [
                "# Placeholder generated by Neurocontainers Builder web validation.",
                `# Source path: ${path}`,
                "# Browser validation checks recipe structure only.",
                "# Local sidecar file contents are not embedded in this validation run.",
                "",
            ].join("\n"),
        ]),
    );

    const count = requiredFiles.length;
    const warnings = [
        `Browser validation created ${count} placeholder file${count === 1 ? "" : "s"} for local recipe assets referenced by \`copy:\` or \`file.filename\`. This validates recipe structure, but not the original sidecar file contents.`,
    ];

    return { files, warnings };
}
